Update portproton
1) reverted shellcheck SC2164 cd error check as it completely broke the script
2) added language vars
3) added terminal messages on errors

diff --git a/usr/bin/portproton b/usr/bin/portproton
--- a/usr/bin/portproton
+++ b/usr/bin/portproton
@@ -6,19 +6,22 @@ unset PW_AUTOPLAY PW_SET_LANG PW_SILENT_INSTALL
 export portname="PortProton"
 export port_ver=1.0
 ########################################################################
+ENG_LANG="English"
+RUS_LANG="Russian (Русский)"
 [ -z "${LANG}" ] && export LANG=C
 deflink="${HOME}/PortWINE/${portname}"
-[ "$(id -u)" -eq 0 ] && echo "The script should NOT be run by root!" && zenity --error --text "The script should NOT be run by root!" 2> /dev/null  && exit 1
-if [ "$(dirname "$(readlink -f "$0")")" == "/usr/bin" ] ; then
+[ "$(id -u)" -eq 0 ] && echo "This script should NOT be run by root!" && zenity --error --text "This script should NOT be run by root!" 2> /dev/null && exit 1
+my_dir=$(dirname "$(readlink -f "$0")")
+if [ "$my_dir" == "/usr/bin" ] ; then
 	[ -z "${XDG_DATA_HOME}" ] && export XDG_DATA_HOME="$HOME/.local/share"
 	if [ -f "${XDG_DATA_HOME}/PortWINE/PortProton/data/scripts/start.sh" ] ; then
 		/usr/bin/env bash "${XDG_DATA_HOME}/PortWINE/PortProton/data/scripts/start.sh" "$@"
 		exit 0
 	else
 		if [ -n "$(locale | grep "LANG=ru_RU.UTF-8")" ] ; then
-			PW_SET_LANG="Russian"
+			PW_SET_LANG=$RUS_LANG
 		else
-			PW_SET_LANG="English"
+			PW_SET_LANG=$ENG_LANG
 		fi
 		export PW_SILENT_INSTALL="1"
 		export PW_AUTOPLAY=1
@@ -40,30 +43,30 @@ if [ "${vexit}" -eq "1" ] ; then
     exit 1
 fi
 ########################################################################
-cd "$(dirname "$(readlink -f "$0")")" || exit
+cd "$my_dir"
 export links
 links="$(pwd)"
 ########################################################################
 if [ "$1" = "-rus" ] ; then
-	PW_SET_LANG="Russian"
+	PW_SET_LANG=$RUS_LANG
 	export PW_SILENT_INSTALL="1"
 elif [ "$1" = "-eng" ] ; then
-	PW_SET_LANG="English"
+	PW_SET_LANG=$ENG_LANG
 	export PW_SILENT_INSTALL="1"
 elif [ -z "${PW_SET_LANG}" ] ; then
-	PW_SET_LANG=$(zenity --title  "Install $portname" --text "Select the installation language" --list --radiolist \
---column="Set:" --column "Language:" \
-	TRUE "Russian" \
-	FALSE "English" ) 2> /dev/null
-	if [ $? -eq 1 ] ; then exit 1 ; fi
+	PW_SET_LANG=$(zenity --title  "Install $portname" --text "Select installation language:" --list --radiolist \
+--column="" --column "Language" \
+	TRUE  "$RUS_LANG" \
+	FALSE "$ENG_LANG" ) 2> /dev/null
+	if [ $? -eq 1 ] ; then echo "Installation language not set!" && exit 1 ; fi
 	case $PW_SET_LANG in
-		"Russian")
+		"$RUS_LANG")
 			INFO_TEXT="Вы запустили установщик PortWINE ${portname} версии ${port_ver}. \n\nЭто некоммерческий продукт и развивается исключительно за идею и Ваши пожертвования. \nВсе права стороннего программного обеспечения принадлежат их владельцам! \nПродолжая установку, Вы автоматически соглашаетесь с данными условиями." > /dev/null 2>&1 ;;
-		"English")
-			INFO_TEXT="You’ve started PortWINE installer ${portname} v. ${port_ver}. \n\nIt is a non-commercial product and is developed only for the idea and with the help of your donations. \nAll third-party software rights belong to their respective owners! \n If you continue the installation, you agree to these terms." > /dev/null 2>&1 ;;
+		"$ENG_LANG")
+			INFO_TEXT="You’ve started PortWINE ${portname} installer v.${port_ver}. \n\nIt is a non-commercial product and is developed only for the idea and with the help of your donations. \nAll third-party software rights belong to their respective owners! \nIf you continue installation, you agree to these terms." > /dev/null 2>&1 ;;
 	esac
-	eval "$(zenity --info --title "INFO" --text "$INFO_TEXT" --no-wrap 2> /dev/null)"
-	if [ $? -eq 1 ] ; then echo "error" && exit 1 ; fi
+	zenity --info --title "INFO" --text "$INFO_TEXT" --no-wrap 2> /dev/null
+	if [ $? -eq 1 ] ; then echo "INFO message not displayed!" && exit 1 ; fi
 fi
 ########################################################################
 if [ "${PW_SILENT_INSTALL}" = "1" ] ; then
@@ -71,12 +74,12 @@ if [ "${PW_SILENT_INSTALL}" = "1" ] ; then
 	D_PATH="${deflink}"
 else
 	case $PW_SET_LANG in
-		"Russian")
+		"$RUS_LANG")
 			inst1=$(zenity --title  "Установка ${portname}" --text "Выберите путь для установки (обновления) PortWINE \nили оставьте его по умолчанию." --list --radiolist --width=350 --height=220 \
-			--column="Выбор" --column "Путь:" \
-			TRUE "${deflink}" \
+			--column="" --column "Путь:" \
+			TRUE  "${deflink}" \
 			FALSE "Другой путь..." ) 2> /dev/null
-			if [ $? -eq 1 ] ; then exit 1 ; fi
+			if [ $? -eq 1 ] ; then echo "Installation path not set!" && exit 1 ; fi
 			case $inst1 in
 				"${deflink}")
 					D_PATH="${deflink}" ;;
@@ -84,12 +87,12 @@ else
 					D_PATH=$(zenity --file-selection --directory --title="Выберите путь..." )
 					D_PATH="${D_PATH}/${portname}" ;;
 			esac ;;
-		"English")
+		"$ENG_LANG")
 			inst1=$(zenity --title  "Install ${portname}" --text "Choose path to install (update) PortWINE \nor leave it as default." --list --radiolist --width=350 --height=220 \
-			--column="Set..." --column "Path:" \
-			TRUE "${deflink}" \
+			--column="" --column "Path:" \
+			TRUE  "${deflink}" \
 			FALSE "Other path..." ) 2> /dev/null
-			if [ $? -eq 1 ];then exit 1; fi
+			if [ $? -eq 1 ] ; then echo "Installation path not set!" && exit 1; fi
 			case $inst1 in
 				"${deflink}")
 					D_PATH="${deflink}" ;;
@@ -102,33 +105,34 @@ else
 fi
 ########################################################################
 case $PW_SET_LANG in
-	"Russian")
+	"$RUS_LANG")
 		progress_bar() {
-		zenity --progress --title="Установка..." --text="Настройка ${portname}" --pulsate --auto-close --auto-kill --width=450 > /dev/null 2>&1
+			zenity --progress --title="Установка..." --text="Настройка ${portname}" --pulsate --auto-close --auto-kill --width=450 > /dev/null 2>&1
 		} ;;
-	"English")
+	"$ENG_LANG")
 		progress_bar() {
-		zenity --progress --title="Install..." --text="Install ${portname}" --pulsate --auto-close --auto-kill --width=450 > /dev/null 2>&1
+			zenity --progress --title="Install..." --text="Install ${portname}" --pulsate --auto-close --auto-kill --width=450 > /dev/null 2>&1
 		} ;;
 esac
 ########################################################################
 export PORT_WINE_PATH="${D_PATH}"
+scripts_dir="${PORT_WINE_PATH}/data/scripts"
 if [ ! -d "${PORT_WINE_PATH}" ] ; then
     mkdir -p "$PORT_WINE_PATH"
 else
 	rm -fr "${PORT_WINE_PATH}/data/tmp"
-	rm -f "${PORT_WINE_PATH}/data/scripts/"* > /dev/null 2>&1
+	rm -f "${scripts_dir}/"* > /dev/null 2>&1
 fi
 ########################################################################
 mkdir -p "${PORT_WINE_PATH}/data/tmp"
 echo "${port_ver}" > "${PORT_WINE_PATH}/data/tmp/${portname}_ver"
 case $PW_SET_LANG in
-	"Russian") echo "RUS" > "${PORT_WINE_PATH}/data/tmp/${portname}_loc" ;;
-	"English") echo "ENG" > "${PORT_WINE_PATH}/data/tmp/${portname}_loc" ;;
+	"$RUS_LANG") echo "RUS" > "${PORT_WINE_PATH}/data/tmp/${portname}_loc" ;;
+	"$ENG_LANG") echo "ENG" > "${PORT_WINE_PATH}/data/tmp/${portname}_loc" ;;
 esac
 ########################################################################
 export PORT_WINE_TMP_PATH="${PORT_WINE_PATH}/data/tmp"
-cd "${PORT_WINE_PATH}" || zenity --error --text "Could NOT change directory to ${PORT_WINE_PATH}!" 2> /dev/null  && exit 1
+cd "${PORT_WINE_PATH}"
 try_download_scripts () {
 	wget -O "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz" -nd -c --read-timeout 300 \
 	--retry-connrefused --timeout 15 --tries 3 \
@@ -142,7 +146,7 @@ try_download_scripts () {
 			rm -f "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
 			rm -fr "${PORT_WINE_TMP_PATH}/PortWINE-master/"
 			export scripts_current_ver
-			scripts_current_ver=$(cat "${PORT_WINE_PATH}/data/scripts/var" | grep SCRIPTS_NEXT_VERSION | awk -F "=" '{print $2}')
+			scripts_current_ver=$(cat "${scripts_dir}/var" | grep SCRIPTS_NEXT_VERSION | awk -F "=" '{print $2}')
 			echo "${scripts_current_ver}" > "${PORT_WINE_TMP_PATH}/scripts_ver"
 		else
 			rm -f "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
@@ -159,7 +163,6 @@ else
 fi
 chmod 755 -R "${PORT_WINE_PATH}"
 ########################################################################
-scrpts="${PORT_WINE_PATH}/data/scripts"
-cd "$scrpts" || zenity --error --text "Could NOT change directory to $scrpts" 2> /dev/null  && exit 1
-/usr/bin/env bash "${PORT_WINE_PATH}/data/scripts/setup.sh" && exit 0
+cd "${scripts_dir}"
+/usr/bin/env bash "${scripts_dir}/setup.sh" && exit 0
 ################################ARCH_BIN################################
